### ISSUE TITLE
Error building SharePointFramework\ProjectWebParts

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#27]
```
> prosjektportalen-spfx-projectwebparts@0.7.2 package C:\code\prosjektportalen365\SharePointFramework\ProjectWebParts
> gulp clean --ship && gulp default --ship && gulp package-solution --ship

Build target: SHIP
[10:49:07] Using gulpfile C:\code\prosjektportalen365\SharePointFramework\ProjectWebParts\gulpfile.js
[10:49:07] Starting gulp
[10:49:07] Starting 'clean'...
[10:49:07] Starting subtask 'clean'...
[10:49:07] Finished subtask 'clean' after 357 ms
[10:49:07] Finished 'clean' after 359 ms
[10:49:08] ==================[ Finished ]==================
[10:49:08] Project prosjektportalen-spfx-projectwebparts version:0.7.2
[10:49:08] Build tools version:3.8.33
[10:49:08] Node version:v8.15.0
[10:49:08] Total duration:10 s
Build target: SHIP
[10:49:22] Using gulpfile C:\code\prosjektportalen365\SharePointFramework\ProjectWebParts\gulpfile.js
[10:49:22] Starting gulp
[10:49:22] Starting 'default'...
[10:49:22] Starting subtask 'configure-sp-build-rig'...
[10:49:22] Finished subtask 'configure-sp-build-rig' after 11 ms
[10:49:22] Starting subtask 'pre-copy'...
[10:49:22] Finished subtask 'pre-copy' after 69 ms
[10:49:22] Starting subtask 'copy-static-assets'...
[10:49:22] Starting subtask 'sass'...
[10:49:23] Finished subtask 'copy-static-assets' after 1.24 s
[10:49:23] Finished subtask 'sass' after 1.3 s
[10:49:23] Starting subtask 'tslint'...
[10:49:23] [tslint] tslint version: 5.9.1
[10:49:24] Starting subtask 'tsc'...
[10:49:24] [tsc] typescript version: 2.4.2
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(32,38): error TS1005: '=' expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(34,46): error TS1005: ';' expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(34,75): error TS1005: ';' expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(34,99): error TS1005: ';' expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,47): error TS1005: ';' expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,48): error TS1109: Expression expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,49): error TS1109: Expression expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,76): error TS1109: Expression expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,100): error TS1005: ';' expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,103): error TS1109: Expression expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,119): error TS1109: Expression expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,144): error TS1005: ';' expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,152): error TS1128: Declaration or statement expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,160): error TS1005: ',' expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(38,50): error TS1005: ';' expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(38,51): error TS1109: Expression expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(38,52): error TS1109: Expression expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(38,69): error TS1005: '(' expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(38,71): error TS1128: Declaration or statement expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(51,30): error TS1005: ';' expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(51,54): error TS1005: ';' expected.
[10:49:43] Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(51,57): error TS1109: Expression expected.
[10:49:43] Error - 'tsc' sub task errored after 19 s 
 exited with code 2
[10:49:43] 'default' errored after 21 s
[10:49:43]
[10:49:43] ==================[ Finished ]==================
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(32,38): error TS1005: '=' expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(34,46): error TS1005: ';' expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(34,75): error TS1005: ';' expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(34,99): error TS1005: ';' expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,47): error TS1005: ';' expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,48): error TS1109: Expression expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,49): error TS1109: Expression expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,76): error TS1109: Expression expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,100): error TS1005: ';' expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,103): error TS1109: Expression expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,119): error TS1109: Expression expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,144): error TS1005: ';' expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,152): error TS1128: Declaration or statement expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(36,160): error TS1005: ',' expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(38,50): error TS1005: ';' expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(38,51): error TS1109: Expression expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(38,52): error TS1109: Expression expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(38,69): error TS1005: '(' expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(38,71): error TS1128: Declaration or statement expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(51,30): error TS1005: ';' expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(51,54): error TS1005: ';' expected.
Error - [tsc] node_modules/.registry.npmjs.org/@types/prop-types/15.7.1/node_modules/@types/prop-types/index.d.ts(51,57): error TS1109: Expression expected.
Error - 'tsc' sub task errored after 19 s 
 exited with code 2
[10:49:45] Project prosjektportalen-spfx-projectwebparts version:0.7.2
[10:49:45] Build tools version:3.8.33
[10:49:45] Node version:v8.15.0
[10:49:45] Total duration:34 s
[10:49:45] Task errors:23
The build failed because a task wrote output to stderr.
Exiting with exit code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prosjektportalen-spfx-projectwebparts@0.7.2 package: `gulp clean --ship && gulp default --ship && gulp package-solution --ship`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prosjektportalen-spfx-projectwebparts@0.7.2 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by olemp** [comment]
Build now works with 1.9.0.
